[package]
name = "live-wait"
version = "0.1.0"
authors = ["Zach Schuermann <zachary.zvs@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.4"
serde_json = "1.0"
tui = "0.8"
termion = "1.5"
sse-client = { version = "1.1", features = ["native-tls"] }
