FROM rustlang/rust:nightly as builder
WORKDIR build
COPY . .
RUN cargo build --release

FROM gcr.io/distroless/cc
COPY --from=builder /build/target/release/live-wait ./
COPY --from=builder /build/Rocket.toml ./
EXPOSE 8080
ENTRYPOINT ["./live-wait"]
